---
# Manifest file downloaded from fusion
externalId: tr-ts_assets_mapping
name: ts_assets_mapping
query: "file:transformation.sql SELECT ts.externalId AS externalId, ast.id AS assetId FROM `_cdf`.`timeseries` AS ts\nINNER JOIN `_cdf`.`assets` AS ast
    ON split(ts.externalId, \":\") [0] = ast.externalId"
destination:
    type: timeseries
ignoreNullFields: true
shared: true
action: update
dataSetExternalId: uc:001:oee:ds
authentication:
    clientId: ${COGNITE_CLIENT_ID}
    clientSecret: ${COGNITE_CLIENT_SECRET}
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
  # Optional: If idP requires providing the scopes
    cdfProjectName: ${CDF_PROJECT_NAME}
    scopes:
        - https://westeurope-1.cognitedata.com/.default
